# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: src/lccfq_backend/api/protos/qpu_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'src/lccfq_backend/api/protos/qpu_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n.src/lccfq_backend/api/protos/qpu_service.proto\"\"\n\x0f\x45xecutorRequest\x12\x0f\n\x07message\x18\x01 \x01(\t\"4\n\x10\x45xecutorResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x0f\n\x07success\x18\x02 \x01(\x08\x32:\n\x0bQPUExecutor\x12+\n\x04Ping\x12\x10.ExecutorRequest\x1a\x11.ExecutorResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'src.lccfq_backend.api.protos.qpu_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EXECUTORREQUEST']._serialized_start=50
  _globals['_EXECUTORREQUEST']._serialized_end=84
  _globals['_EXECUTORRESPONSE']._serialized_start=86
  _globals['_EXECUTORRESPONSE']._serialized_end=138
  _globals['_QPUEXECUTOR']._serialized_start=140
  _globals['_QPUEXECUTOR']._serialized_end=198
# @@protoc_insertion_point(module_scope)
